# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: eshop
metadata:
  template: azd-init@1.20.0

hooks:
  postprovision:
    shell: sh
    run: |
      #!/bin/sh
      set -e
      echo "Post-provisioning steps..."

      echo "Building docker-image locally..."
      docker-compose build
      echo "Docker-image built successfully."

      echo "Post-provisioning completed."

services:
  eshop-api:
    host: containerapp
    project: ./src/
    language: dotnet
    docker:
      context: .
      path: Dockerfile
      image: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}/eshop-api-${AZURE_ENV_NAME}
      tag: latest
      platform: linux/amd64
      registry: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}
      remoteBuild: false
resources:
  eshop-api:
    type: host.containerapp
    port: 8080
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
      - name: ASPNETCORE_HTTP_PORTS
        value: "8080"
