# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: eshop
metadata:
    template: azd-init@1.20.0
services:
    eshop-api:
        project: src
        host: containerapp
        language: dotnet
        docker:
            path: Dockerfile
            image: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}/eshop-api-${AZURE_ENV_NAME}
            tag: latest
            platform: linux/amd64
            registry: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}
            remoteBuild: true

resources:
    eshop-api:
        type: host.containerapp
        port: 8080

hooks:
    postprovision:
        shell: pwsh
        run: |
            #!/usr/bin/env pwsh

            Write-Host "Post-provisioning steps..."

            Write-Host "Building docker-image locally..."
            docker-compose build
            Write-Host "Docker-image built successfully."

            Write-Host "Post-provisioning completed."
