# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: eshop-api
metadata:
    template: azd-init@1.20.0
services:
    eShop-api:
        project: src/eShopAPI.csproj
        host: containerapp
        language: dotnet
        docker:
            path: src/Dockerfile
            context: .
            image: $AZURE_CONTAINER_REGISTRY_ENDPOINT/eshopapi
            tag: latest
            platform: linux/amd64
            registry: $AZURE_CONTAINER_REGISTRY_ENDPOINT
            remoteBuild: false
resources:
    eShop-api:
        type: host.containerapp
        port: 8080
