services:
  eshopapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "80:8080"
      - "81:8081"
    volumes:
      - ${APPDATA}:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}:/root/.microsoft/usersecrets:ro
      - ${APPDATA}:/home/app/.aspnet/https:ro
      - ${APPDATA}:/root/.aspnet/https:ro