services:
  eshopapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - eshop-secrets:/home/app/.microsoft/usersecrets:ro
      - eshop-secrets:/root/.microsoft/usersecrets:ro
      - eshop-https:/home/app/.aspnet/https:ro
      - eshop-https:/root/.aspnet/https:ro

volumes:
  eshop-secrets:
    driver: external
    driver_opts:
      type: none
      device: ${APPDATA}/Microsoft/UserSecrets
      o: bind

  eshop-https:
    driver: external
    driver_opts:
      type: none
      device: ${APPDATA}/ASP.NET/Https
      o: bind
  