version: '3.4'

services:
  eshop-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    networks:
      - eshop-vnet
    ports:
      - "8080"
      - "8081"
    volumes:
      - eshop-data:/home/app/:rw

networks:
  eshop-vnet:
    name: eshop-vnet 
    

volumes:
  eshop-data:
    name: eshop-data
    driver: local