services:
  eshop-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      - eshop-vnet
    ports:
      - "8080"
      - "8081"
    volumes:
      - eshop-secrets:/home/app/.microsoft/usersecrets:rw
      - eshop-https:/home/app/.aspnet/https:rw
      - eshop-data:/home/app/:rw
      - eshop-appdata:/app/:rw

networks:
  eshop-vnet:
    name: eshop-vnet
    driver: bridge

volumes:
  eshop-data:
    name: eshop-data
    driver: local

  eshop-secrets:
    name: eshop-secrets
    driver: local

  eshop-https:
    name: eshop-https
    driver: local

  eshop-appdata:
    name: eshop-appdata
    driver: local