version: '3.4'

services:
  sqlDb:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123#@!qweEWQ
    networks:
      - eshopnet
    ports:
      - 1433:1433
    volumes:
      - eshop-sqldata:/var/opt/mssql/data
  eshopapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTIONSTRING=./data/dbpassword
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      - eshopnet
    ports:
      - 8080:8080

networks:
  eshopnet:
    name: eshopnet
    driver: bridge

volumes:
  eshop-sqldata:
    name: eshop-sqldata
    external: false
