version: '3.4'

services:
  eshopdb:
    container_name: eshopdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD="123#@!qweEWQ"
    secrets:
      - dbpassword
    volumes:
      - eshopdbvolume:/etc/data
    networks:
      - eshopnet
    ports:
      - 1433:1433
  
  eshopapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - CONNECTIONSTRING=./data/dbpassword
    secrets:
      - dbpassword 
    networks:
      - eshopnet
    ports:
      - 5000:8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - eshopdb

networks:
  eshopnet:
    name: eshopnet
    driver: bridge
    
volumes:
    eshopdbvolume:
      name: eshopdbvolume

secrets:
  dbpassword:
    name: dbpassword
    file: ./data/dbpassword.txt
