version: '3.4'

services:
  eshopapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTIONSTRING=./data/dbpassword
      - ASPNETCORE_HTTP_PORTS=8080
    secrets:
      - dbpassword 
    networks:
      - eshopnet
    ports:
      - 8080:8080

networks:
  eshopnet:
    name: eshopnet
    driver: bridge
    
volumes:
  sqlsystem:
    name: sqlsystem  
  sqldata:
    name: sqldata
  sqllog:
    name: sqllog
  sqlbackup:
    name: sqlbackup

secrets:
  dbpassword:
    name: dbpassword
    file: ./data/dbpassword.txt
