version: '3.4'

services:
  eshopDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=/run/secrets/dbPassword
    secrets:
      - dbPassword
    volumes:
      - eshopDbVolume:/etc/data
    networks:
      - eShopNet
  eshopapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - CONNECTIONSTRING= /run/secrets/dbPassword
    secrets:
      - dbPassword 
    networks:
      - eShopNet
    ports:
      - "5000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - eshopDb

networks:
  eShopNet:
    driver: bridge

volumes:
  eshopDbVolume:

secrets:
  dbPassword:
    file: ./data/dbPassword.txt
