version: '3.4'

services:
  sqlDb:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    networks:
      - eshopnet
    ports:
      - 6060:1433
    volumes:
      - eshopapi-sqldata:/var/opt/mssql
  eshopapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTIONSTRING=./data/dbpassword
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      - eshopnet
    ports:
      - 8080:8080

networks:
  eshopnet:
    name: eshopnet
    driver: bridge

volumes:
  eshopapi-sqldata:
    name: eshopapi-sqldata
    external: false
