version: '3.4'

services:
  eshopapi:
    container_name: eshopapi
    image: ${REGISTRY:-eshop}/eshop-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: eShopAPI/Dockerfile
