apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopapi-deployment
  namespace: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-api
  template:
    metadata:
      labels:
        app: eshop-api
    spec:
      containers:
      - name: eshop-api
        image: eshop/eshop-api:linux-latest
        resources:
        ports:
          - containerPort: 8080
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_HTTP_PORTS
            value: "8080"
        envFrom:
          - secretRef:
              name: eshop-secret
