apiVersion: v1
kind: Service
metadata:
  name: eshopapi-service
  namespace: eshop
spec:
  type: LoadBalancer
  selector:
    app: eshop-api
  ports:
    - protocol: TCP
      port: 80    
      targetPort: 80
