# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: eShop API CI - DotNet Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./src/eShopLocalVSDev/eShopAPI/
      run: dotnet restore eShopAPI.csproj
    - name: Build eShop API
      working-directory: ./src/eShopLocalVSDev/eShopAPI/
      run: dotnet build eShopAPI.csproj --no-restore