name: eShop API CI - Docker Compose Buil Image

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        working-directory: ./src/eShopAPIOnContainers/eShopOnKubernetes/eShopAPI/eShopAPI/
        run: dotnet restore eShopAPI.csproj
      - name: Build eShop API
        working-directory: ./src/eShopAPIOnContainers/eShopOnKubernetes/eShopAPI/eShopAPI/
        run: dotnet build eShopAPI.csproj --no-restore
          
  build-and-push-eshop-api-docker-image:
    needs: build-application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push eShop API Docker image to Azure Container Registry
        working-directory: ./src/eShopAPIOnContainers/eShopOnKubernetes/eShopAPI/
        run: | 
          docker-compose build

          az acr login --name creshop
          docker push creshop.azurecr.io/eshop/eshop-api:linux-latest

  deploy-eshop-api-to-azure-kubernetes-service:
    needs: build-and-push-eshop-api-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy eShop API to Azure Kubernetes Services
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az acr login --name creshop --expose-token
            az aks get-credentials --resource-group eShop-rg --name aks-eShop        
      - uses: azure/setup-kubectl@v2.0      
      - uses: Azure/k8s-deploy@v4
        with:
           manifests: |
            ./src/eShopAPIOnContainers/eShopOnKubernetes/eShopAPI/deploy/AKS/SharedResources
            ./src/eShopAPIOnContainers/eShopOnKubernetes/eShopAPI/deploy/AKS/
      - uses: Azure/k8s-deploy@v4
        with:
            namespace: eshop
            manifests: |
              ./src/eShopAPIOnContainers/eShopOnKubernetes/eShopAPI/deploy/AKS/